server:
  port: 9003

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: image-route
          uri: lb://IMAGE-SERVER
          predicates:
            - Path=/api/upload/**
          filters:
            - StripPrefix=2
        - id: item-route
          uri: lb://ITEM-SERVER
          predicates:
            - Path=/api/item/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9002/eureka
    registry-fetch-interval-seconds: 5
